spring:
  application:
    name: p10
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-turbo
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms